### ISSUE TITLE
Extension suggestions

### ISSUE THREAD

**Issue by danilofreire** [bat67/markdown-extension-pack#1]
Hello! 

Congrats on the nice extension, it's very convenient! I'd just like to suggest, if you're interested, to add the [Markdown Emoji](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-emoji) and [Markdown Table Prettifier](https://marketplace.visualstudio.com/items?itemName=darkriszty.markdown-table-prettify) extensions to the pack too. They might be useful for some. Thanks!

**Comment by bat67** [comment]
Thanks for this issue~~😃 I added the Markdown Emoji and Markdown Table Prettifier extensions to the pack. 
Please download and have fun! @danilofreire
